/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef RAZERSDK_AUTODEFS_H
#define RAZERSDK_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_RAZERSDK_NAME "RazerSDK"
#define S3E_EXT_RAZERSDK_HASH 0xffce9cab

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("RazerSDK", 19)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !RAZERSDK_AUTODEFS_H */
